### ISSUE TITLE
The bug of the $_GET,$_POST,$_SERVER couldn't print

### ISSUE THREAD

**Issue by skadiD** [ammarfaizi2/php-integral-obfuscator#3]
Just like title said,When I try to print these variables，there are nothing to show.
An example:
`<?php
var_dump($_GET['a']);
?>`

**Comment by ammarfaizi2** [comment]
I am working on it.

**Comment by ammarfaizi2** [comment]
This bug has already been fixed in d718a9905d4fd75a5124aa7a02b26238a367304d

Thank you for your report.

**Comment by skadiD** [comment]
Thank you very much.
